---
- hosts: all

  vars_files:
    - default.vars.yml
    - vault.yml

  pre_tasks:
    - name: Include playbook variables
      ansible.builtin.include_vars: vars.yml

    - name: Add user with sudo permissions
      ansible.builtin.user:
        name: "{{ user }}"
        groups: su, sudo
        append: true

    - name: Change connection details to the hardened ones
      ansible.builtin.set_fact:
        ansible_port: "{{ port }}"
        ansible_user: "{{ user }}"

  collections:
    - devsec.hardening

  roles:
    - os_hardening
    - ssh_hardening

  tasks:
    - name: Test new connection
      ansible.builtin.ping:
