---
- hosts: all
  vars:
    systemd_config: /etc/systemd/system.conf
  become: true

  pre_tasks:
    - name: Import task for adding sudo SSH user
      ansible.builtin.import_tasks: tasks/sudo_ssh_user.yml

    # Workaround for php packages installation issues of install_nextcloud role
    - name: Backup existing systemd config
      ansible.builtin.copy:
        remote_src: true
        src: "{{ systemd_config }}"
        dest: "{{ systemd_config }}.bak"
        mode: preserve

    - name: Disable start rate limiting for systemd units
      ansible.builtin.lineinfile:
        path: "{{ systemd_config }}"
        regexp: "^DefaultStartLimitIntervalSec="
        line: "DefaultStartLimitIntervalSec=0"
        state: present
      notify: Force systemd to reread configs

    # Requirement of nginx_hardening roles
    - name: Install nginx
      ansible.builtin.package:
        name: "nginx"
        state: present
      when: nextcloud_websrv == "nginx"

  collections:
    - devsec.hardening

  roles:
    - role: os_hardening
    - role: ssh_hardening
    - role: nginx_hardening
    - role: fail2ban
    - role: ufw
      when: nextcloud_websrv == "nginx"
    - role: nextcloud.admin.install_nextcloud

  tasks:
    # Introduced by nginx hardening
    - name: Remove shared memory zone
      ansible.builtin.lineinfile:
        path: "{{ nginx_configuration_dir }}/conf.d/90.hardening.conf"
        regexp: "^limit_conn"
        state: absent
      when: nextcloud_websrv == "nginx"

  # Continuation of workaround
  post_tasks:
    - name: Restore systemd config
      ansible.builtin.copy:
        remote_src: true
        src: "{{ systemd_config }}.bak"
        dest: "{{ systemd_config }}"
      notify: Force systemd to reread configs

  handlers:
    - name: Force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: true
