---
- name: Import variables
  vars_files: default.vars.yml
  ansible.builtin.include_vars:
    - vault.yml
    - vars.yml

- name: Add user with sudo permissions
  ansible.builtin.user:
    name: {{ user }}
    groups: su, sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_file: {{ key_file }}

- name: Harden SSH
  roles:
    - devsec.hardening.ssh-hardening
  vars:
    ssh_server_ports: [{{ port }}]
  ansible.builtin.meta: flush_handlers

- name: Reset connection with new sudo user and hardened port
  ansible.builtin.set_fact:
    ansible_port: {{ port }}
    ansible_user: {{ user}}
    ansible_private_key_file: {{ key_file }}
  ansible.builtin.meta: reset_connection

- name: Test new SSH port
  ansible.builtin.ping:
