---
- name: Configure the VPS
  hosts: all
  vars:
    systemd_config: /etc/systemd/system.conf
  become: true

  pre_tasks:
    # Requirement of nginx_hardening role
    - name: Install nginx
      ansible.builtin.package:
        name: "nginx"
        state: present
      when: nextcloud_websrv == "nginx"
    # Requirement of ufw role
    - name: Install UFW
      ansible.builtin.package:
        name: "ufw"
        state: present

  roles:
    - role: devsec.hardening.ssh_hardening
      tags: hardening
    - role: geerlingguy.certbot
      tags: certbot

  tasks:
    # Workaround for php packages installation issues of install_nextcloud role
    - name: Backup existing systemd config
      ansible.builtin.copy:
        remote_src: true
        src: "{{ systemd_config }}"
        dest: "{{ systemd_config }}.bak"
        mode: preserve

    - name: Disable start rate limiting for systemd units
      ansible.builtin.lineinfile:
        path: "{{ systemd_config }}"
        regexp: "^DefaultStartLimitIntervalSec="
        line: "DefaultStartLimitIntervalSec=0"
        state: present
      notify: Force systemd to reread configs

    - name: Make config changes have effect
      ansible.builtin.meta: flush_handlers

    - name: Install and configure Nextcloud with workaround
      block:
        - name: Install and configure Nextcloud
          ansible.builtin.include_role:
            name: nextcloud.admin.install_nextcloud
      rescue:
        # Continuation of workaround
        - name: Restore systemd config
          ansible.builtin.copy:
            remote_src: true
            src: "{{ systemd_config }}.bak"
            dest: "{{ systemd_config }}"
            mode: preserve
          notify: Force systemd to reread configs

    - name: OS hardening
      ansible.builtin.include_role:
        name: devsec.hardening.os_hardening
      tags: hardening

    - name: Nginx hardening
      ansible.builtin.include_role:
        name: devsec.hardening.nginx_hardening
      when: nextcloud_websrv == "nginx"
      tags: hardening

    - name: Fail2Ban
      ansible.builtin.include_role:
        name: fail2ban

    - name: UFW
      ansible.builtin.include_role:
        name: ufw


  post_tasks:
    # Introduced by nginx hardening role
    - name: Remove shared memory zone
      ansible.builtin.lineinfile:
        path: "{{ nginx_configuration_dir }}/conf.d/90.hardening.conf"
        regexp: "^limit_conn"
        state: absent
      when: nextcloud_websrv == "nginx"

  handlers:
    - name: Force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: true
