---
- hosts: all
  vars:
    systemd_config: /etc/systemd/system.conf

  pre_tasks:
    - name: Import task for adding sudo SSH user
      ansible.builtin.import_tasks: tasks/sudo_ssh_user.yml

    - name: Backup existing systemd config
      ansible.builtin.copy:
        remote_src: true
        src: "{{ systemd_config }}"
        dest: "{{ systemd_config }}.bak"
        mode: preserve
      become: true

    - name: Disable start rate limiting for systemd units
      ansible.builtin.lineinfile:
        path: "{{ systemd_config }}"
        regexp: "^DefaultStartLimitIntervalSec="
        line: "DefaultStartLimitIntervalSec=0"
        state: present
      become: true
      notify: Force systemd to reread configs

#  collections:
#    - devsec.hardening
#
  roles:
    - {role: nextcloud.admin.install_nextcloud, become: true}
#    - {role: os_hardening, become: true}
#    - {role: ssh_hardening, become: true}
#
#  tasks:
#    - name: Import other tasks
#      ansible.builtin.import_tasks:
#        - tasks/
#        - tasks/ufw.yml

  post_tasks:
    - name: Restore systemd config
      ansible.builtin.copy:
        remote_src: true
        src: "{{ systemd_config }}.bak"
        dest: "{{ systemd_config }}"
      become: true
      notify: Force systemd to reread configs

  handlers:
    - name: Force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: true
      become: true
