---
- hosts: all

  vars_files:
    - default.vars.yml
    - vault.yml

  pre_tasks:
    - name: Include playbook variables
      ansible.builtin.include_vars: vars.yml
      ignore_errors: true

    - name: Add user with sudo permissions
      ansible.builtin.user:
        name: "{{ user }}"
        groups: sudo
        append: true
        password: "{{ password|password_hash('sha512') }}"
      become: true

    - name: Update connection details with new user
      ansible.builtin.set_fact:
        ansible_user: "{{ user }}"
        ansible_password: "{{ password }}"
        ansible_become_password: "{{ password }}"

    - name: Reset connection
      ansible.builtin.meta: reset_connection

  collections:
    - devsec.hardening

  roles:
    - { role: os_hardening, become: yes }
    - { role: ssh_hardening, become: yes }

  tasks:
    - name: Test new connection
      ansible.builtin.ping:
