---
# tasks file for ufw
- name: Allow all access to SSH ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ssh_server_ports }}"

- name: Allow all access to tcp port 80
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow all access to tcp port 443
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Enable UFW
  community.general.ufw:
    state: enabled
